
inq: inq.o reporter.o
	gcc -pedantic -Wall -o inq -lbluetooth inq.o reporter.o

inq.o: inq.c
	gcc -c -pedantic -Wall -o inq.o inq.c

reporter.o: reporter.c
	gcc -c -pedantic -Wall -o reporter.o reporter.c
